### ISSUE TITLE
MultiPV weird behaviour 

### ISSUE THREAD

**Issue by fonkap** [jdart1/arasan-chess#10]
I tested the following position (simple one pawn ending) with MultiPV 6,

![image](https://user-images.githubusercontent.com/4880919/31575170-acab488a-b0e0-11e7-8066-b9b685ae6465.png)

With the following commands:

Arasan 20.2 Copyright 1994-2017 by Jon Dart. All Rights Reserved.
uci
id name Arasan 20.2
id author Jon Dart
option name Hash type spin default 32 min 4 max 64000
option name Ponder type check default true
option name Use tablebases type check default false
option name Tablebases type combo var None var Syzygy default None
option name SyzygyTbPath type string default syzygy
option name SyzygyUse50MoveRule type check default true
option name SyzygyProbeDepth type spin default 4 min 0 max 64
option name MultiPV type spin default 1 min 1 max 10
option name OwnBook type check default true
option name Book selectivity type spin default 50 min 0 max 100
option name Threads type spin default 1 min 1 max 64
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 2600 min 1000 max 2600
uciok
setoption name MultiPV value 6
ucinewgame
position fen 3k4/8/4KP2/8/8/8/8/8 w - - 1 132
go movetime 1000

.... and I got :

info multipv 1 depth 1 score cp 24617 time 0 nodes 11 hashfull 0 pv e6d5
info multipv 2 depth 1 score cp 24617 time 0 nodes 19 hashfull 0 pv e6e5
info multipv 3 depth 1 score cp 24617 time 0 nodes 26 hashfull 0 pv e6f5
info multipv 4 depth 1 score cp 24617 time 0 nodes 32 hashfull 0 pv e6d6
info multipv 5 depth 1 score cp 24617 time 0 nodes 37 hashfull 0 pv e6f7
info multipv 6 depth 1 score cp 24617 time 0 nodes 37 hashfull 0 pv f6f7 d8c7

[lots of output]

info multipv 1 depth 24 score mate 13 time 669 nodes 2043726 nps 3054896 hashfull 188 pv e6f7 d8d7
info multipv 2 depth 24 score **mate 7 time 881 nodes 2848157 nps 3232868 hashfull 188 pv f6f7** d8c7 f7f8q c7b6 f8d6 b6a5 e6d5 a5b5 d6b8 b5a5 d5c5 a5a6 b8b6
info multipv 3 depth 24 score mate 13 time 978 nodes 3181561 nps 3253129 hashfull 188 pv e6f5 d8d7
info multipv 4 depth 24 score cp 0 time 978 nodes 3181756 nps 3253329 hashfull 188 pv e6d6 d8e8 d6e6 e8d8
info multipv 5 depth 24 score cp 0 time 979 nodes 3182678 nps 3250947 hashfull 188 pv e6d5 d8e8 d5e6 e8d8
info multipv 6 depth 24 score cp 0 time 979 nodes 3182780 nps 3251052 hashfull 188 pv e6e5 d8e8 e5e6 e8d8
info multipv 1 depth 24 score mate 13 time 669 nodes 2043726 nps 3054896 hashfull 188 pv e6f7 d8d7
info multipv 2 depth 24 score mate 7 time 881 nodes 2848157 nps 3232868 hashfull 188 pv f6f7 d8c7 f7f8q c7b6 f8d6 b6a5 e6d5 a5b5 d6b8 b5a5 d5c5 a5a6 b8b6
info multipv 3 depth 24 score mate 13 time 978 nodes 3181561 nps 3253129 hashfull 188 pv e6f5 d8d7
info multipv 4 depth 24 score cp 0 time 978 nodes 3181756 nps 3253329 hashfull 188 pv e6d6 d8e8 d6e6 e8d8
info multipv 5 depth 24 score cp 0 time 979 nodes 3182678 nps 3250947 hashfull 188 pv e6d5 d8e8 d5e6 e8d8
info multipv 6 depth 24 score cp 0 time 979 nodes 3182793 nps 3251065 hashfull 188 pv e6e5 d8e8 e5e6 e8d8
info depth 25 currmove e6e5 currmovenumber 0
info depth 25 currmove e6d5 currmovenumber 1
info depth 25 currmove e6d6 currmovenumber 2
info depth 25 currmove e6f5 currmovenumber 3
info score cp 18 lowerbound
info depth 25 currmove e6f5 currmovenumber 3
info depth 25 currmove e6f5 currmovenumber 0
info score cp 56 lowerbound
info depth 25 currmove e6f5 currmovenumber 0
info depth 25 currmove e6f5 currmovenumber 0
info score cp 131 lowerbound
info depth 25 currmove e6f5 currmovenumber 0
info depth 25 currmove e6f5 currmovenumber 0
info score cp 281 lowerbound
info depth 25 currmove e6f5 currmovenumber 0
info depth 25 currmove e6f5 currmovenumber 0
info score cp 581 lowerbound
info depth 25 currmove e6f5 currmovenumber 0
info depth 25 currmove e6f5 currmovenumber 0
info score mate 13 lowerbound
info depth 25 currmove e6f5 currmovenumber 0
info depth 25 currmove e6e5 currmovenumber 1
info depth 25 currmove e6d5 currmovenumber 2
info depth 25 currmove e6d6 currmovenumber 3
info depth 25 currmove f6f7 currmovenumber 4
info multipv 1 depth 25 score mate 19 time 1010 nodes 3275409 nps 3242979 hashfull 189
bestmove e6f5

You can see, how it finds the best move (f6f7 mate in 7) , but then gives an extra line with depth 25, and a wrong bestmove.

I suppose this isn't the supposed behaviour.

**Comment by fonkap** [comment]
I am using current master branch, but I also tested the released binaries version 20.2.
Please ask me for any further information needed.

By the way, very nice engine, thank you very very much.

**Comment by jdart1** [comment]
The extra line problem should be fixed by commit 4555292.

**Comment by fonkap** [comment]
Thank you for your quick response. 
But I think the main problem is still present.

Looking into code, it seems that successive iterations of the loop:

` for (multipv_count=0; multipv_count < srcOpts.multipv && !terminate; multipv_count++)`

Will overwrite the value of `node->best` choosing always the last pv.

One very easy to reproduce example would be initial position and MultiPV > 1 , and no book:

Arasan ARASAN_VERSION Copyright 1994-2017 by Jon Dart. All Rights Reserved.
uci
id name Arasan ARASAN_VERSION
id author Jon Dart
option name Hash type spin default 32 min 4 max 2000
option name Ponder type check default true
option name MultiPV type spin default 1 min 1 max 10
option name OwnBook type check default true
option name Book selectivity type spin default 50 min 0 max 100
option name Threads type spin default 1 min 1 max 64
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 2600 min 1000 max 2600
uciok
setoption name OwnBook value false
setoption name MultiPV value 10
go depth 1
[some output]
info multipv 1 depth 1 score cp 57 time 1 nodes 21 hashfull 0 pv e2e3
info multipv 2 depth 1 score cp 56 time 1 nodes 41 hashfull 0 pv e2e4
info multipv 3 depth 1 score cp 53 time 2 nodes 60 hashfull 0 pv b1c3
info multipv 4 depth 1 score cp 53 time 2 nodes 78 hashfull 0 pv g1f3
info multipv 5 depth 1 score cp 50 time 2 nodes 95 hashfull 0 pv d2d3
info multipv 6 depth 1 score cp 48 time 3 nodes 111 hashfull 0 pv d2d4
info multipv 7 depth 1 score cp 21 time 3 nodes 126 hashfull 0 pv b2b3
info multipv 8 depth 1 score cp 21 time 4 nodes 140 hashfull 0 pv g2g3
info multipv 9 depth 1 score cp 20 time 4 nodes 153 hashfull 0 pv b2b4
info multipv 10 depth 1 score cp 20 time 40 nodes 165 nps 4125 hashfull 0 pv g2g4
bestmove g2g4

g2g4 is reported as bestmove!

I'm trying but I cant find a proper fix for the code.
Thank you so much for your time.

**Comment by jdart1** [comment]
Ok, will look into it.

**Comment by jdart1** [comment]
I have pushed another fix for the wrong bestmove issue - 2a2e75a.

**Comment by fonkap** [comment]
Looks fine now. 
Thank you very much!
